### ISSUE TITLE
Move to a more generic implementation of "distinct"

### ISSUE THREAD

**Issue by vasil9v** [appcelerator/lexus#4]
part of "Cleanup of Lexus Spec"

**Comment by whitfin** [comment]
The context here is that histograms can provide the same options that `group_by` currently does, allowing them to share the same implementation under the hood. Currently `distinct` offers a subset of the `group_by` functionality.

**Comment by whitfin** [comment]
As a follow up, we have decided to remove the "distinct" method entirely, to be replaced by groups in future. You can achieve the existing functionality using groupings even after the method is removed.

At the same time, we will rename `group_by` to `groups` to be syntactically similar with `filters`.
